networks:
  ros-network:
    driver: bridge

services:
  talker_image:
    image: docker_minimal_example:ros_talker_listener
    container_name: ros_talker_image
    privileged: true
    # network_mode: host
    runtime: nvidia
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_DOMAIN_ID=0
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"
    command: >
      bash -c 'ros2 run demo_nodes_cpp talker && \
              tail -F anything'
    stdin_open: true
    tty: true
    networks:
      - ros-network

  listenner_image:
    image: docker_minimal_example:ros_talker_listener
    container_name: ros_listenner_image
    privileged: true
    # network_mode: host
    runtime: nvidia
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_DOMAIN_ID=0
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"
    command: >
      bash -c 'ros2 run demo_nodes_cpp listener && \
              tail -F anything'
    stdin_open: true
    tty: true
    networks:
      - ros-network
      